<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro" name="kangaroo">
  
  <!-- USING GLOBAL PROPERTIES: [collision_type, sim_type] -->
  <!-- LOCAL PROPERTIES -->
  <xacro:property name="eps_radians" value="0.008" /> <!-- 0.45deg -->
  <xacro:property name="eps_meters" value="0.005" />
  <xacro:property name="leg_1_min_pos" value="${-15.0 *deg_to_rad}" />
  <xacro:property name="leg_1_max_pos" value="${40.0 *deg_to_rad}" />
  <xacro:property name="leg_2_min_pos" value="${-42.5 *deg_to_rad}" />
  <xacro:property name="leg_2_max_pos" value="${38.0 *deg_to_rad}" />
  <xacro:property name="leg_3_min_pos" value="${-27.0 *deg_to_rad}" />
  <xacro:property name="leg_3_max_pos" value="${27.0 *deg_to_rad}" />
  <xacro:property name="leg_femur_min_pos" value="${10.0 *deg_to_rad}" />
  <xacro:property name="leg_femur_max_pos" value="${70.0 *deg_to_rad}" />
  <xacro:property name="leg_knee_min_pos" value="${20.0 *deg_to_rad}" />
  <xacro:property name="leg_knee_max_pos" value="${140.0 *deg_to_rad}" />
  <xacro:property name="leg_min_length" value="0.131973" />
  <xacro:property name="leg_max_length" value="0.71416639" />
  
  <!-- INCLUDES -->

  <!-- <xacro:include filename="$(find kangaroo_description)/urdf/leg/leg.transmission.xacro" /> -->
  <xacro:include filename="$(find kangaroo_description)/urdf/ankle/ankle.urdf.xacro" />


  <xacro:macro name="kangaroo_leg"
    params="side reflect parent *origin leg_type:=leg">
    <link name="leg_${side}_1_link">
      <inertial>
        <origin xyz="0.0063167 ${reflect * 0.0045949} -0.0083828" rpy="0 0 0" />
        <mass value="2.7478" />
        <inertia ixx="0.0019336" ixy="${reflect * 8.5058E-06}" ixz="${reflect * 4.8385E-05}"
          iyy="0.0018225" iyz="${reflect * -7.282E-06}" izz="0.001426" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://kangaroo_description/meshes/leg/leg_${side}_1_link.stl"
            scale="1 1 1" />
        </geometry>
        <material name="pal/DarkGrey" />
      </visual>
      <xacro:link_collision 
        mujoco="${sim_type in ['mujoco-ros2-control', 'mujoco']}"
        collision_type="${collision_type}"
        mesh_file="package://kangaroo_description/meshes/leg/leg_${side}_1_link.stl"
        scale="1 1 1"
        capsule_radius="0.0795723341519774"
        capsule_length="0.0826993462928503">
          <properties>
            <xacro:origin xyz="0 0 0" rpy="0 0 0" condition="${collision_type == 'mesh'}"/>
            <xacro:origin xyz="0.0460974381954039 ${reflect * 2.61722121352298e-07} -0.0031296116923038" rpy="0 0 0" condition="${collision_type == 'capsule'}"/>
          </properties>
      </xacro:link_collision>
    </link>
    <joint name="leg_${side}_1_joint" type="revolute">
      <xacro:insert_block name="origin" />
      <parent link="${parent}" />
      <child link="leg_${side}_1_link" />
      <axis xyz="0 0 1" />
      <xacro:if value="${reflect == 1}">
        <limit lower="${leg_1_min_pos}" upper="${leg_1_max_pos}" effort="80" velocity="3.87" />
      </xacro:if>
      <xacro:if value="${reflect == -1}">
        <limit lower="${reflect * leg_1_max_pos}" upper="${reflect * leg_1_min_pos}" effort="80" velocity="3.87" />
      </xacro:if>
    </joint>
    <link name="leg_${side}_2_link">
      <inertial>
        <origin
          xyz="-0.0029278 -9.6207E-05 1.0866E-09"
          rpy="0 0 0" />
        <mass value="0.0905312454913012" />
        <inertia ixx="6.10166860944865E-06" ixy="4.64490555644666E-08" ixz="4.07017223451518E-13"
          iyy="3.88541683636482E-05" iyz="-1.04538188015163E-12" izz="3.6228659424845E-05" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://kangaroo_description/meshes/leg/leg_${side}_2_link.stl"
            scale="1 1 1" />
        </geometry>
        <material name="pal/DarkGrey" />
      </visual>
      <xacro:link_collision 
        mujoco="${sim_type in ['mujoco-ros2-control', 'mujoco']}"
        collision_type="${collision_type}"
        mesh_file="package://kangaroo_description/meshes/leg/leg_${side}_2_link.stl"
        scale="1 1 1">
          <properties>
            <xacro:origin xyz="0 0 0" rpy="0 0 0" condition="${collision_type == 'mesh'}"/>
            <xacro:origin xyz="0 0 0" rpy="0 0 0" condition="${collision_type == 'capsule'}"/>
          </properties>
      </xacro:link_collision>
    </link>
    <joint name="leg_${side}_2_joint" type="revolute">
      <origin xyz="0.015024 0 -0.1175" rpy="0 0 0" />
      <parent link="leg_${side}_1_link" />
      <child link="leg_${side}_2_link" />
      <axis xyz="0 1 0" />
      <limit lower="${leg_2_min_pos}" upper="${leg_2_max_pos}" effort="230" velocity="3.87" />
    </joint>
    <link name="leg_${side}_3_link">
      <inertial>
        <origin xyz="-0.033949 ${reflect * 0.049989} -0.030543" rpy="0 0 0" />
        <mass value="3.658" />
        <inertia ixx="0.0025968" ixy="${reflect * 0.00018723}" ixz="${reflect * -0.00014976}"
          iyy="0.0031521" iyz="${reflect * 3.7258E-05}" izz="0.0032376" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://kangaroo_description/meshes/leg/leg_${side}_3_link.stl"
            scale="1 1 1" />
        </geometry>
        <material name="pal/DarkGrey" />
      </visual>
      <xacro:link_collision 
        mujoco="${sim_type in ['mujoco-ros2-control', 'mujoco']}"
        collision_type="${collision_type}"
        mesh_file="package://kangaroo_description/meshes/leg/leg_${side}_3_link.stl"
        scale="1 1 1"
        capsule_radius="0.107806017781018"
        capsule_length="0.0968239136648226">
          <properties>
            <xacro:origin xyz="0 0 0" rpy="0 0 0" condition="${collision_type == 'mesh'}"/>
            <xacro:origin xyz="-0.0336733479063389 ${reflect * 0.0385644774263234} -0.0356634521697478" rpy="0 0 0" condition="${collision_type == 'capsule'}"/>
          </properties>
      </xacro:link_collision>
    </link>
    <joint name="leg_${side}_3_joint" type="revolute">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="leg_${side}_2_link" />
      <child link="leg_${side}_3_link" />
      <axis xyz="1 0 0" />
      <limit lower="${leg_3_min_pos}" upper="${leg_3_max_pos}" effort="139" velocity="3.87" />
    </joint>
    <link name="leg_${side}_femur_link">
      <inertial>
        <origin xyz="0.0527475093314697 0.000135688427874925 -0.146959283149568" rpy="0 0 0" />
        <mass value="3.94567187082779" />
        <inertia ixx="0.0111010751306264" ixy="2.24256967982894E-05" ixz="0.0025879993168672"
          iyy="0.0121128398206334" iyz="-1.93362671261787E-05" izz="0.0025734913670898" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <!-- The ballscrews are removed from the meshes for better visualization, but they are
        used for inertia computation etc -->
          <mesh filename="package://kangaroo_description/meshes/leg/leg_femur_link.stl" />
        </geometry>
        <material name="pal/DarkGrey" />
      </visual>
      <xacro:link_collision 
        mujoco="${sim_type in ['mujoco-ros2-control', 'mujoco']}"
        collision_type="${collision_type}"
        mesh_file="package://kangaroo_description/meshes/leg/leg_4_collision_link.stl"
        scale="1 ${reflect} 1"
        capsule_radius="0.0910718312767096"
        capsule_length="0.391268198141901">
          <properties>
            <xacro:origin xyz="0 0 0" rpy="0 ${60.0 * deg_to_rad} 0" condition="${collision_type == 'mesh'}"/>
            <xacro:origin xyz="${-0.0527475093314697 + 0.120708412192612} ${reflect * 0.0010415825568705} ${-0.146959283149568 + 0.0229981018461956}" rpy="0 ${-15.0 * deg_to_rad} 0" condition="${collision_type == 'capsule'}"/>
          </properties>
      </xacro:link_collision>
    </link>
    <link name="leg_${side}_knee_link">
      <inertial>
        <origin xyz="-0.0569664873635563 -5.41309796184553E-05 -0.148820781933269" rpy="0 0 0" />
        <mass value="1.02238189690276" />
        <inertia ixx="0.00193955870555937" ixy="-7.22330237538467E-08" ixz="-0.000472475893337071"
          iyy="0.00215347079183119" iyz="1.36520012214457E-06" izz="0.000391378760186175" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://kangaroo_description/meshes/leg/leg_tibia_link.stl" />
        </geometry>
        <material name="pal/DarkGrey" />
      </visual>
      <xacro:link_collision 
        mujoco="${sim_type in ['mujoco-ros2-control', 'mujoco']}"
        collision_type="${collision_type}"
        mesh_file="package://kangaroo_description/meshes/leg/leg_5_collision_link.stl"
        scale="1 ${reflect} 1"
        capsule_radius="0.055"
        capsule_length="0.3">
          <properties>
            <xacro:origin xyz="0 0 0" rpy="0 ${-60.0 * deg_to_rad} 0" condition="${collision_type == 'mesh'}"/>
            <xacro:origin xyz="-0.0569664873635563 ${reflect * 7.99553099622616e-06} -0.148820781933269" rpy="0 ${30.0 * deg_to_rad} 0" condition="${collision_type == 'capsule'}"/>
          </properties>
      </xacro:link_collision>
    </link>

    <!-- We approximate the virtual length link with a small cylinder mass and inertia -->
    <xacro:property name="m"   value="0.1" /> <!-- mass -->
    <xacro:property name="r"   value="0.01" /> <!-- radius -->
    <xacro:property name="h"   value="0.1" /> <!-- height -->

    <link name="leg_${side}_length_link">
      <inertial>
        <xacro:if value="${use_mimic}">
          <origin rpy="0 0 0" xyz="0.0 0.0 -0.2"/>
          <mass value="6.0" /> 
          <inertia ixx="0.05" ixy="0.0" ixz="0.0" iyy="0.05" iyz="0.0" izz="0.016875" />
        </xacro:if>
        <xacro:unless value="${use_mimic}">
          <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
          <mass value="${m}" /> 
          <inertia ixx="${(1./12.)*m*(3.*r*r + h*h)}" ixy="0.0" ixz="0.0" iyy="${(1./12.)*m*(3.*r*r + h*h)}" 
            iyz="0.0" izz="${(1./2.)*m*r*r}" />
        </xacro:unless>
      </inertial>
      <visual>
        <origin rpy="0 0 0" xyz="0 0 ${(leg_min_length - leg_max_length)/2}"/>
        <geometry>
          <cylinder length="${(leg_max_length - leg_min_length)}" radius="0.00005"/>
        </geometry>
        <material name="pal/DarkGrey" />
      </visual>
    </link>
    <joint name="leg_${side}_length_joint" type="prismatic">
     <origin xyz="0 ${reflect * 0.0669} -0.09" rpy="0 ${180 * deg_to_rad} 0" />
      <parent link="leg_${side}_3_link" />
      <child link="leg_${side}_length_link" />
      <axis xyz="0 0 1" />
      <limit lower="${leg_min_length}" upper="${leg_max_length}" effort="1100" velocity="10.0" />
    </joint>

    <joint name="leg_${side}_femur_joint" type="revolute">
      <origin xyz="0 ${reflect * 0.0669} -0.09" rpy="0 ${-70.0 * deg_to_rad} 0" />
      <parent link="leg_${side}_3_link" />
      <child link="leg_${side}_femur_link" />
      <axis xyz="0 1 0" />
      <limit lower="${leg_femur_min_pos}" upper="${leg_femur_max_pos}" effort="100" velocity="3.87" />
      <xacro:if value="${use_mimic}">
      	<mimic joint="leg_${side}_length_joint" multiplier="1.69435" offset="-0.096145"/>
      </xacro:if>
    </joint>

    <joint name="leg_${side}_knee_joint" type="revolute">
      <origin xyz="0.129944529468438 0 -0.357091611860635" rpy="0 ${140.0 * deg_to_rad} 0" />
      <parent link="leg_${side}_femur_link" />
      <child link="leg_${side}_knee_link" />
      <axis xyz="0 -1 0" />
      <limit lower="${leg_knee_min_pos}" upper="${leg_knee_max_pos}" effort="100" velocity="3.87" />
      <xacro:if value="${use_mimic}">
      	<mimic joint="leg_${side}_length_joint" multiplier="3.38877" offset="-0.19229"/>
      </xacro:if>
    </joint>

    <link name="leg_${side}_knee_straight" />
    <joint name="leg_${side}_knee_straight_joint" type="fixed">
      <parent link="leg_${side}_knee_link" />
      <child link="leg_${side}_knee_straight" />
      <origin rpy="0 ${-70.0 * deg_to_rad} 0" xyz="0 0 0" />
    </joint>
    <link name="leg_${side}_knee_lower_bearing" />
    <joint name="leg_${side}_knee_lower_bearing_joint" type="fixed">
      <parent link="leg_${side}_knee_straight" />
      <child link="leg_${side}_knee_lower_bearing" />
      <origin rpy="0 0 0" xyz="-0.38 0.0 0.0" />
    </joint>

    <xacro:kangaroo_ankle side="${side}" parent="leg_${side}_length_link" reflect="${reflect}"
      roll_joint="5" pitch_joint="4" read_actuator="leg_${side}_length_motor">
      <origin xyz="0.0 0 0.0" rpy="0 ${200 *deg_to_rad} 0" />
    </xacro:kangaroo_ankle>

  </xacro:macro>

</robot>
