<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro" name="kangaroo">

  <xacro:include filename="$(find kangaroo_description)/urdf/leg/leg.transmission.xacro" />
  <xacro:include filename="$(find kangaroo_description)/urdf/ankle/ankle.urdf.xacro" />

  <xacro:property name="deg_to_rad"       value="0.01745329251994329577" />
  <xacro:property name="eps_radians"      value="0.008" /> <!-- 0.45deg -->
  <xacro:property name="eps_meters"       value="0.005" />
  <xacro:property name="leg_1_min_pos"   value="${-15.0 *deg_to_rad}" />
  <xacro:property name="leg_1_max_pos"   value="${40.0 *deg_to_rad}" />
  <xacro:property name="leg_2_min_pos"   value="${-42.5 *deg_to_rad}" />
  <xacro:property name="leg_2_max_pos"   value="${42.5 *deg_to_rad}" />
  <xacro:property name="leg_3_min_pos"   value="${-27.0 *deg_to_rad}" />
  <xacro:property name="leg_3_max_pos"   value="${27.0 *deg_to_rad}" />
  <xacro:property name="leg_femur_min_pos"   value="${10.0 *deg_to_rad}" />
  <xacro:property name="leg_femur_max_pos"   value="${70.0 *deg_to_rad}" />
  <xacro:property name="leg_knee_min_pos"   value="${20.0 *deg_to_rad}" />
  <xacro:property name="leg_knee_max_pos"   value="${140.0 *deg_to_rad}" />
  <xacro:property name="leg_min_length"   value="0.131973" />
  <xacro:property name="leg_max_length"   value="0.71416639" />

  <xacro:macro name="mimic_joint_plugin_gazebo" params="name_prefix parent_joint mimic_joint has_pid:=false multiplier:=1.0 offset:=0 sensitiveness:=0.0 max_effort:=1.0 robot_namespace:=''">
    <gazebo>
      <plugin name="${name_prefix}mimic_joint_plugin" filename="libroboticsgroup_gazebo_mimic_joint_plugin.so">
        <joint>${parent_joint}</joint>
        <mimicJoint>${mimic_joint}</mimicJoint>
        <xacro:if value="${has_pid}">                     <!-- if set to true, PID parameters from "/gazebo_ros_control/pid_gains/${mimic_joint}" are loaded -->
          <hasPID />
        </xacro:if>
        <multiplier>${multiplier}</multiplier>
        <offset>${offset}</offset>
        <sensitiveness>${sensitiveness}</sensitiveness>   <!-- if absolute difference between setpoint and process value is below this threshold, do nothing; 0.0 = disable [rad] -->
        <maxEffort>${max_effort}</maxEffort>              <!-- only taken into account if has_pid:=true [Nm] -->
        <xacro:unless value="${robot_namespace == ''}">
          <robotNamespace>${robot_namespace}</robotNamespace>
        </xacro:unless>
      </plugin>
    </gazebo>
  </xacro:macro>

  <xacro:macro name="kangaroo_leg" params="side reflect parent *origin hipz_model simulation:=false use_mimic:=true ft_sensors:=false">
    <link name="leg_${side}_1_link">
      <inertial>
        <origin xyz="0.00567848436743906 ${reflect *0.00485639369944225} 0.0095021298057529" rpy="0 0 0" />
        <mass value="2.65497387095349" />
        <inertia ixx="0.00149978199388072" ixy="${reflect * 9.84571170148762E-06}" ixz="${reflect * 2.47542814609499E-05}"
          iyy="0.00145455726255875" iyz="${reflect * -1.83660235416355E-05}" izz="0.00128461512366971" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://kangaroo_description/meshes/leg_1_link.stl" scale="1 ${reflect} 1"/>
        </geometry>
        <material name="">
          <color rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://kangaroo_description/meshes/leg_1_link.stl"  scale="1 ${reflect} 1"/>
        </geometry>
      </collision>
    </link>
    <joint name="leg_${side}_1_joint" type="revolute">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}" />
      <child link="leg_${side}_1_link" />
      <axis xyz="0 0 1" />
      <xacro:if value="${reflect == 1}">
        <limit lower="${leg_1_min_pos}" upper="${leg_1_max_pos}" effort="150" velocity="3.87" />
      </xacro:if>
      <xacro:if value="${reflect == -1}">
        <limit lower="${reflect * leg_1_max_pos}" upper="${reflect * leg_1_min_pos}" effort="500" velocity="3.87" />
      </xacro:if>
    </joint>
    <link name="leg_${side}_2_link">
      <inertial>
        <origin
          xyz="-0.00292779640030026 -9.62074367728827E-05 1.0865936483917E-09"
          rpy="0 0 0" />
        <mass value="0.0905312454913012" />
        <inertia ixx="6.10166860944865E-06" ixy="4.64490555644666E-08" ixz="4.07017223451518E-13"
          iyy="3.88541683636482E-05" iyz="-1.04538188015163E-12" izz="3.6228659424845E-05" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://kangaroo_description/meshes/leg_2_link.stl" scale="1 ${reflect} 1"/>
        </geometry>
        <material name="">
          <color rgba="0.894117647058823 0.913725490196078 0.929411764705882 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://kangaroo_description/meshes/leg_2_link.stl" scale="1 ${reflect} 1"/>
        </geometry>
      </collision>
    </link>
    <joint name="leg_${side}_2_joint" type="revolute">
      <origin xyz="0.015024 0 -0.0925" rpy="0 0 0" />
      <parent link="leg_${side}_1_link" />
      <child link="leg_${side}_2_link" />
      <axis xyz="0 1 0" />
      <limit lower="${leg_2_min_pos}" upper="${leg_2_max_pos}" effort="150" velocity="3.87" />
    </joint>
    <link name="leg_${side}_3_link">
      <inertial>
        <origin xyz="-0.0331126340475435 ${reflect * 0.0492000964734808} -0.0300270306298204" rpy="0 0 0" />
        <mass value="3.45187520713338" />
        <inertia ixx="0.0021995228245877" ixy="${reflect * 0.000142021792686858}" ixz="${reflect * -0.000114089540435782}"
          iyy="0.00286983872145199" iyz="${reflect * 3.27704238559214E-05}" izz="0.00273461620254835" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://kangaroo_description/meshes/leg_3_link.stl" scale="1 ${reflect} 1"/>
        </geometry>
        <material name="">
          <color rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://kangaroo_description/meshes/leg_3_link.stl" scale="1 ${reflect} 1"/>
        </geometry>
      </collision>
    </link>
    <joint name="leg_${side}_3_joint" type="revolute">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="leg_${side}_2_link" />
      <child link="leg_${side}_3_link" />
      <axis xyz="1 0 0" />
      <limit lower="${leg_3_min_pos}" upper="${leg_3_max_pos}" effort="150" velocity="3.87" />
    </joint>
    <link name="leg_${side}_femur_link">
<!--       <xacro:if value="${use_mimic}">
              <mass value="0.1" />
              <inertia ixx="1.E-5" ixy="0.0" ixz="0.0" iyy="1.E-5" iyz="0.0" izz="1.E-5" />
      </xacro:if>
      <xacro:unless value="${use_mimic}">
        <mass value="3.57408268817521" />
              <inertia ixx="0.00247170768644724" ixy="2.87874888621229E-05" ixz="0.00247469186737281"
                iyy="0.0126050262407564" iyz="1.01404330133204E-05" izz="0.0116319632922522" />
      </xacro:unless> -->
      <inertial>
        <origin xyz="0.0527475093314697 0.000135688427874925 -0.146959283149568" rpy="0 0 0" />
        <mass value="3.94567187082779" />
        <inertia ixx="0.0111010751306264" ixy="2.24256967982894E-05" ixz="0.0025879993168672"
          iyy="0.0121128398206334" iyz="-1.93362671261787E-05" izz="0.0025734913670898" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <!-- The ballscrews are removed from the meshes for better visualization, but they are used for inertia computation etc -->
          <mesh filename="package://kangaroo_description/meshes/leg_femur_link.stl" />
        </geometry>
        <material name="">
          <color rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <!-- The ballscrews are removed from the meshes for better visualization, but they are used for inertia computation etc -->
          <mesh filename="package://kangaroo_description/meshes/leg_femur_link.stl" />
        </geometry>
      </collision>
    </link>
    <link name="leg_${side}_knee_link">
<!--       <xacro:if value="${use_mimic}">
              <mass value="0.1" />
              <inertia ixx="1.E-5" ixy="0.0" ixz="0.0" iyy="1.E-5" iyz="0.0" izz="1.E-5" />
      </xacro:if>
      <xacro:unless value="${use_mimic}">
              <mass value="0.87223211672797" />
              <inertia ixx="0.000350603269949793" ixy="6.37793331536252E-07" ixz="-0.000461550351107159"
                iyy="0.00242184402988972" iyz="5.09327556678297E-07" izz="0.0022368624903808" />
      </xacro:unless> -->
      <inertial>
        <origin xyz="-0.0569664873635563 -5.41309796184553E-05 -0.148820781933269" rpy="0 0 0" />
        <mass value="1.02238189690276" />
        <inertia ixx="0.00193955870555937" ixy="-7.22330237538467E-08" ixz="-0.000472475893337071"
          iyy="0.00215347079183119" iyz="1.36520012214457E-06" izz="0.000391378760186175" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://kangaroo_description/meshes/leg_tibia_link.stl" />
        </geometry>
        <material name="">
          <color rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://kangaroo_description/meshes/leg_tibia_link.stl" />
        </geometry>
      </collision>
    </link>

    <!-- We approximate the virtual length link with a small cylinder mass and inertia -->
    <xacro:property name="m"   value="0.1" /> <!-- mass -->
    <xacro:property name="r"   value="0.01" /> <!-- radius -->
    <xacro:property name="h"   value="0.1" /> <!-- height -->

    <link name="leg_${side}_length_link">
      <inertial>
<xacro:if value="${use_mimic}">
        <origin rpy="0 0 0" xyz="0.0 0.0 -0.2"/>
        <mass value="6.0" /> 
        <inertia ixx="0.05" ixy="0.0" ixz="0.0" iyy="0.05" iyz="0.0" izz="0.016875" />
</xacro:if>
<xacro:unless value="${use_mimic}">
        <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
        <mass value="${m}" /> 
        <inertia ixx="${(1./12.)*m*(3.*r*r + h*h)}" ixy="0.0" ixz="0.0" iyy="${(1./12.)*m*(3.*r*r + h*h)}" 
		iyz="0.0" izz="${(1./2.)*m*r*r}" />
</xacro:unless>
      </inertial>
      <visual>
        <origin rpy="0 0 0" xyz="0 0 ${(leg_min_length - leg_max_length)/2}"/>
        <geometry>
          <cylinder length="${(leg_max_length - leg_min_length)}" radius="0.00005"/>
        </geometry>
        <material name="DarkGrey" />
      </visual>
    </link>
    <joint name="leg_${side}_length_joint" type="prismatic">
     <origin xyz="0 ${reflect * 0.0669} -0.09" rpy="0 ${180 * deg_to_rad} 0" />
      <parent link="leg_${side}_3_link" />
      <child link="leg_${side}_length_link" />
      <axis xyz="0 0 1" />
      <limit lower="${leg_min_length}" upper="${leg_max_length}" effort="1500" velocity="10" />
    </joint>

    <joint name="leg_${side}_femur_joint" type="revolute">
      <origin xyz="0 ${reflect * 0.0669} -0.09" rpy="0 ${-70.0 * deg_to_rad} 0" />
      <parent link="leg_${side}_3_link" />
      <child link="leg_${side}_femur_link" />
      <axis xyz="0 1 0" />
      <limit lower="${leg_femur_min_pos}" upper="${leg_femur_max_pos}" effort="100" velocity="3.87" />
      <xacro:if value="${use_mimic}">
      	<mimic joint="leg_${side}_length_joint" multiplier="1.69435" offset="-0.096145"/>
      </xacro:if>
    </joint>

    <joint name="leg_${side}_knee_joint" type="revolute">
      <origin xyz="0.129944529468438 0 -0.357091611860635" rpy="0 ${140.0 * deg_to_rad} 0" />
      <!-- <origin xyz="0.37413 0 -0.066509" rpy="0 ${-70.0 * deg_to_rad} 0" /> -->
      <parent link="leg_${side}_femur_link" />
      <child link="leg_${side}_knee_link" />
      <axis xyz="0 -1 0" />
      <limit lower="${leg_knee_min_pos}" upper="${leg_knee_max_pos}" effort="100" velocity="3.87" />
      <xacro:if value="${use_mimic}">
      	<mimic joint="leg_${side}_length_joint" multiplier="3.38877" offset="-0.19229"/>
      </xacro:if>
    </joint>
    
    <link name="leg_${side}_knee_straight"/>
    <joint name="leg_${side}_knee_straight_joint" type="fixed">
    	<parent link="leg_${side}_knee_link"/>
    	<child link="leg_${side}_knee_straight"/>
    	<origin rpy="0 ${-70.0 * deg_to_rad} 0" xyz="0 0 0"/>
    </joint>
    <link name="leg_${side}_knee_lower_bearing"/>
    <joint name="leg_${side}_knee_lower_bearing_joint" type="fixed">
    	<parent link="leg_${side}_knee_straight"/>
    	<child link="leg_${side}_knee_lower_bearing"/>
    	<origin rpy="0 0 0" xyz="-0.38 0.0 0.0"/>
    </joint>

    <xacro:kangaroo_ankle side="${side}" parent="leg_${side}_length_link" reflect="${reflect}" roll_joint="5" pitch_joint="4" read_actuator="leg_${side}_length_motor" ft_sensors="$(arg ft_sensors)">
      <origin xyz="0.0 0 0.0" rpy="0 ${180 *deg_to_rad} 0" />
    </xacro:kangaroo_ankle>

    <!-- Load corresponding transmission info -->
    <xacro:unless value="${simulation}">
      <xacro:hip_transmission_yaw side="${side}" params_ns="/${side}_hip_z_${hipz_model}_params" />
      <xacro:hip_transmission_roll_pitch side="${side}" roll_joint="3" pitch_joint="2" />
      <xacro:kangaroo_leg_length_actuator_transmission side="${side}" number1="4" number2="5" params_ns="/leg_params" />
    </xacro:unless>
    <xacro:if value="${simulation}">
      <xacro:kangaroo_lower_body_simple_simulation_transmission side="${side}"/>
    </xacro:if>

    <gazebo reference="leg_${side}_1_link">
      <mu1>0.9</mu1>
      <mu2>0.9</mu2>
    </gazebo>
    <gazebo reference="leg_${side}_2_link">
      <mu1>0.9</mu1>
      <mu2>0.9</mu2>
    </gazebo>
    <gazebo reference="leg_${side}_3_link">
      <mu1>0.9</mu1>
      <mu2>0.9</mu2>
    </gazebo>  
    <gazebo reference="leg_${side}_length_link">
      <mu1>0.9</mu1>
      <mu2>0.9</mu2>
    </gazebo>
    <!-- <gazebo reference="leg_${side}_4_link">
      <mu1>0.9</mu1>
      <mu2>0.9</mu2>
    </gazebo>
    <gazebo reference="leg_${side}_5_link">
      <mu1>0.9</mu1>
      <mu2>0.9</mu2>
    </gazebo> -->

   <gazebo reference="leg_${side}_1_joint">
      <implicitSpringDamper>1</implicitSpringDamper>
   </gazebo>
   <gazebo reference="leg_${side}_2_joint">
      <implicitSpringDamper>1</implicitSpringDamper>
   </gazebo>
   <gazebo reference="leg_${side}_3_joint">
      <implicitSpringDamper>1</implicitSpringDamper>
   </gazebo>
    <!-- <gazebo reference="leg_${side}_4_joint">
      <implicitSpringDamper>1</implicitSpringDamper>
   </gazebo>
   <gazebo reference="leg_${side}_5_joint">
      <implicitSpringDamper>1</implicitSpringDamper>
   </gazebo> -->
   <gazebo reference="leg_${side}_length_link">
      <implicitSpringDamper>1</implicitSpringDamper>
   </gazebo>

   <gazebo reference="leg_${side}_1_link">
     <material>Gazebo/FlatWhite</material>
   </gazebo>
   <gazebo reference="leg_${side}_2_link">
     <material>Gazebo/FlatWhite</material>
   </gazebo>
   <gazebo reference="leg_${side}_3_link">
     <material>Gazebo/FlatWhite</material>
   </gazebo>
   <!-- <gazebo reference="leg_${side}_4_link">
     <material>Gazebo/FlatBlack</material>
   </gazebo>
   <gazebo reference="leg_${side}_5_link">
     <material>Gazebo/FlatBlack</material>
   </gazebo> -->
   <gazebo reference="leg_${side}_length_link">
     <material>Gazebo/FlatBlack</material>
   </gazebo>

   <xacro:if value="${use_mimic}">
   	<xacro:mimic_joint_plugin_gazebo name_prefix="" parent_joint="leg_${side}_length_joint" mimic_joint="leg_${side}_knee_joint" has_pid="false" multiplier="3.38877" offset="-0.19229" max_effort="100.0"/>
   	<xacro:mimic_joint_plugin_gazebo name_prefix="" parent_joint="leg_${side}_length_joint" mimic_joint="leg_${side}_femur_joint" has_pid="false" multiplier="1.69435" offset="-0.096145" max_effort="100.0"/>
   </xacro:if>
   <xacro:unless value="${use_mimic}">
	   <gazebo reference="">
		<joint type="revolute" name="leg_${side}_closed_kin_joint">
	              <pose>0 0 0 0 0 0</pose>
		      <parent>leg_${side}_knee_link</parent>
		      <child>leg_${side}_length_link</child>
		      <axis>
			<xyz>0 1 0</xyz>
		      </axis>
    		</joint>
	   </gazebo> 
   </xacro:unless>
   
  </xacro:macro>

</robot>
