#!/usr/bin/env python

import sys
import yaml

def main():
    # Default key and file path
    key = "robot_type"
    output_path = "/tmp/robot_type.yaml"

    # Get value from command line args
    if len(sys.argv) < 2:
        print("Usage: robot_type <value>")
        sys.exit(1)

    value = sys.argv[1]

    # Write to YAML file
    with open(output_path, "w") as f:
        yaml.dump({key: value}, f, default_flow_style=False)

if __name__ == "__main__":
    main()

