play_motion:
  motions:
    home_arms:
      joints: [arm_left_1_joint, arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint]
      points:
        - time_from_start: 0
          positions: [0.24776, 1.5708, 1.5699, 0.79906, -0.2481, 1.5712, -1.5701, 0.79906]
      meta:
        name: home_arms
        usage: ""
        description: arms symmetrical on the side of the torso