approach_planner:
  planning_groups: # Sorted by order of preference
    - left_leg
    - right_leg
    - both_legs
    - left_arm
    - right_arm
    - both_arms
    - pelvis
    - both_arms_pelvis
    - left_arm_pelvis
    - right_arm_pelvis
    - legs_pelvis 
    - everything
  joint_tolerance: 0.01
  skip_planning_approach_vel: 0.5
  skip_planning_approach_min_dur: 0.5
