teleop:
  walk:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: cmd_vel
    deadman_buttons: [4]
    axis_mappings:
      -
        axis: 1
        target: linear.x
        scale: 0.15
      -
        axis: 0
        target: angular.z
        scale: 0.25
      -
        axis: 2
        target: linear.y
        scale: 0.15

  joy_priority:
    type: action
    action_name: joy_priority_action
    buttons: [0]

  # undocumented poses, with 'back' button
  home:
    type: action
    action_name: play_motion
    action_goal:
      motion_name: homing
    buttons: [8, 1]

