teleop:
  walk:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: /biped_walking_dcm_controller/cmd_vel
    deadman_buttons: [4]
    axis_mappings:
      -
        axis: 1
        target: linear.x
        scale: 0.16
      -
        axis: 2
        target: angular.z
        scale: 0.3
      -
        axis: 0
        target: linear.y
        scale: 0.

  joy_priority:
    type: action
    action_name: joy_priority_action
    buttons: [0]
    allow_multiple_commands: False

  # undocumented poses, with 'back' button
  
  both_wave:
    type: action
    action_name: play_motion
    action_goal:
      motion_name: both_wave
    buttons: [0, 5]
    allow_multiple_commands: False

  arms_run:
    type: action
    action_name: play_motion
    action_goal:
      motion_name: arms_run
    buttons: [1, 5]
    allow_multiple_commands: False

  left_wave:
    type: action
    action_name: play_motion
    action_goal:
      motion_name: left_wave
    buttons: [2, 5]
    allow_multiple_commands: False

  home:
    type: action
    action_name: play_motion
    action_goal:
      motion_name: full_homing
    buttons: [3, 5]
    allow_multiple_commands: False

  crouch_boxing:
    type: action
    action_name: play_motion
    action_goal:
      motion_name: crouch_boxing
    buttons: [0, 4]
    allow_multiple_commands: False

  crouch_unboxing:
    type: action
    action_name: play_motion
    action_goal:
      motion_name: crouch_unboxing
    buttons: [2, 4]
    allow_multiple_commands: False

  restart_deployer:
    type: action
    action_name: remote_shell_control
    action_goal:
      cmd: "pal-stop deployer && ps aux | grep deployer | grep -v grep | awk '{print $2}' | xargs kill || true && pal-stop ros_bringup && sleep 5s && pal-start ros_bringup && sleep 5s && pal-start deployer"
    buttons: [3, 4, 5, 6, 7]
    allow_multiple_commands: False

  position_controllers:
    type: action
    action_name: change_controllers
    action_goal:
      start_controllers: ["left_leg_controller", "right_leg_controller", "left_arm_controller", "right_arm_controller", "pelvis_controller"]
      stop_controllers: ["biped_walking_dcm_controller"]
      switch_controllers: True
      unload: True
    buttons: [0, 9]
    allow_multiple_commands: False


  dcm_controller:
    type: action
    action_name: change_controllers
    action_goal:
      start_controllers: ["biped_walking_dcm_controller"]
      load: True
    buttons: [1, 9]
    allow_multiple_commands: False

  reactive_walk_action:
    type: action
    action_name: remote_shell_control
    action_goal:
      cmd: "rosrun pal_lip_mpc_actions reactive_walk_mpc"
    buttons: [2, 9]
    allow_multiple_commands: False
