actuators:
  raw_data:
    position_port: act_position
    velocity_port: act_velocity
    effort_port: act_current
    mode_port: act_control_mode
    position_cmd_port: ref_position
    velocity_cmd_port: ref_velocity
    effort_cmd_port: ref_current
    mode_cmd_port: ref_control_mode
    absolute_encoder_position_port: act_abs_position
    torque_sensor_port: act_torque
    temperature_sensor_port: act_temperature
    current_limit_cmd_port: ref_limit_current
    pids_port: act_pids
    ff_term_port: act_ff_term
    pids_cmd_port: ref_pids
    ff_term_cmd_port: ref_ff_term

e_stop:
  raw_data:
    e_stop_port: emergency_stop_state

#ros_control_component:
#  ignore_read_errors: true

imu:
  base_imu:
    frame: imu_link
    raw_data:
      orientation_port: orientation_base
      linear_acceleration_port: linear_acceleration_base
      angular_velocity_port: angular_velocity_base
    transformation:
      orientation_to_enu_frame: [3.14159265358979, 0.0, 1.570796327]

