play_motion:
  disable_motion_planning: true
  skip_planning: true
  motions:
    homing:
      joints: [leg_left_1_joint, leg_left_2_joint, leg_left_3_joint, leg_left_length_joint, leg_left_4_joint, leg_left_5_joint, leg_right_1_joint, leg_right_2_joint, leg_right_3_joint, leg_right_length_joint, leg_right_4_joint, leg_right_5_joint]
      points:
        - time_from_start: 3.
          positions: [0., 0.05, 0., 0.7, -0.05, 0., 0., 0.05, 0., 0.7, -0.05, 0.]
      meta:
        name: homing
        usage: ""
        description: Move to home configuration
