leg_left_1_joint:
  actuator_params:
    torque_sensor_offset: 0.
leg_left_2_joint:
  actuator_params:
    torque_sensor_offset: 0.
leg_left_3_joint:
  actuator_params:
    torque_sensor_offset: 0.
leg_left_4_joint:
  actuator_params:
    torque_sensor_offset: 0.
leg_left_5_joint:
  actuator_params:
    torque_sensor_offset: 0.
leg_left_length_joint:
  actuator_params:
    torque_sensor_offset: 0.
leg_right_1_joint:
  actuator_params:
    torque_sensor_offset: 0.
leg_right_2_joint:
  actuator_params:
    torque_sensor_offset: 0.0
leg_right_3_joint:
  actuator_params:
    torque_sensor_offset: 0.
leg_right_4_joint:
  actuator_params:
    torque_sensor_offset: 0.0
leg_right_5_joint:
  actuator_params:
    torque_sensor_offset: 0.
leg_right_length_joint:
  actuator_params:
    torque_sensor_offset: 0.
