ball_screw_efficiency: 0.0
ball_screw_lead: 0.0
motor_torque_constant: -0.069
torque_sensor_offset: 0.0
reduction_ratio: 121.0
actuator_names:
  - arm_right_2_motor
check_mode: false

motor_inertia: 4.9e-06
static_friction: 0.05
viscous_friction: 0.05
joint_elasticity: 2033.0
joint_elasticity_damping: 1
