motor_torque_constant: 0.0
torque_sensor_offset: 0.0
reduction_ratio: 0.0
actuator_names:
  - leg_right_5_motor
check_mode: false

# This parametres are random, they have not been identified
motor_inertia: 0.0
static_friction: 0.0
viscous_friction: 0.0
joint_elasticity: 0.0
joint_elasticity_damping: 0