ball_screw_efficiency: 0.9
ball_screw_lead: 0.005
motor_inertia: 0.000009
motor_torque_constant: 0.103
torque_sensor_offset: 0.0
reduction_ratio: 5
actuator_names:
  - pelvis_2_motor
check_mode: false
static_friction: 0.0
viscous_friction: 0.0
joint_elasticity: 10000.0
joint_elasticity_damping: -20.
