right_leg_controller:
  type: "position_controllers/JointTrajectoryController"
  check_mode: True
  joints:
    - leg_right_1_joint
    - leg_right_2_joint
    - leg_right_3_joint
    - leg_right_length_joint
    - leg_right_4_joint
    - leg_right_5_joint
  constraints:
    goal_time: &goal_time_constraint 0.6
    stopped_velocity_tolerance: &stopped_velocity_constraint 0.05
    leg_right_1_joint:
      goal: &goal_pos_constraint 0.02
    leg_right_2_joint:
      goal: *goal_pos_constraint
    leg_right_3_joint:
      goal: *goal_pos_constraint
    leg_right_length_joint:
      goal: *goal_pos_constraint
    leg_right_4_joint:
      goal: *goal_pos_constraint
    leg_right_5_joint:
      goal: *goal_pos_constraint

  stop_trajectory_duration: 0.0
