actuator_gains:
  leg_left_1_motor:
    current: {kd: 0.0, ki: 12000.0, kp: 1.5}
    position: {kd: 3.2e-07, ki: 0.0003, kp: 0.0004}
    velocity: {kd: 6.0e-04, ki: 12.0, kp: 1.2}
  leg_left_2_motor:
    current: {kd: 0.0, ki: 15000.0, kp: 1.65}
    position: {kd: 3.0e-07, ki: 0.000003, kp: 0.0003}
    velocity: {kd: 2.5e-05, ki: 12.0, kp: 1.2}
  leg_left_3_motor:
    current: {kd: 0.0, ki: 12000.0, kp: 1.48}
    position: {kd: 2.0e-08, ki: 0.000003, kp: 0.0003}
    velocity: {kd: 6.0e-04, ki: 12.0, kp: 1.4}
  leg_left_4_motor:
    current: {kd: 0.0, ki: 15000.0, kp: 1.65}
    position: {kd: 3.0e-07, ki: 0.0003, kp: 0.0003}
    velocity: {kd: 6.0e-05, ki: 12.0, kp: 1.2}
  leg_left_5_motor:
    current: {kd: 0.0, ki: 15000.0, kp: 1.63}
    position: {kd: 3.5e-07, ki: 0.0003, kp: 0.0004}
    velocity: {kd: 6.0e-04, ki: 12.0, kp: 1.2}
  leg_left_length_motor:
    current: {kd: 0.0, ki: 4000.0, kp: 0.8}
    position: {kd: 0.00003, ki: 0.002, kp: 0.015}
    velocity: {kd: 3.0e-05, ki: 12.0, kp: 1.5}
  leg_right_1_motor:
    current: {kd: 0.0, ki: 15000.0, kp: 1.65}
    position: {kd: 7.5e-07, ki: 0.0003, kp: 0.0005}
    velocity: {kd: 6.0e-05, ki: 12.0, kp: 1.2}
  leg_right_2_motor:
    current: {kd: 0.0, ki: 12000.0, kp: 1.5}
    position: {kd: 5.0e-08, ki: 0.000003, kp: 0.0003}
    velocity: {kd: 6.8e-04, ki: 10.0, kp: 1.0}
  leg_right_3_motor:
    current: {kd: 0.0, ki: 12000.0, kp: 1.5}
    position: {kd: 5.0e-08, ki: 0.000003, kp: 0.0003}
    velocity: {kd: 6.0e-04, ki: 12.0, kp: 1.2}
  leg_right_4_motor:
    current: {kd: 0.0, ki: 12000.0, kp: 1.5}
    position: {kd: 5.0e-08, ki: 0.0003, kp: 0.0005}
    velocity: {kd: 6.0e-04, ki: 12.0, kp: 1.0}
  leg_right_5_motor:
    current: {kd: 0.0, ki: 12500.0, kp: 1.51}
    position: {kd: 6.0e-07, ki: 0.0003, kp: 0.0006}
    velocity: {kd: 6.0e-04, ki: 12.0, kp: 1.2}
  leg_right_length_motor:
    current: {kd: 0.0, ki: 4000.0, kp: 0.8}
    position: {kd: 0.00003, ki: 0.002, kp: 0.015}
    velocity: {kd: 4.0e-05, ki: 12.0, kp: 1.5}
  pelvis_1_motor:
    current: {kd: 0.0, ki: 520.0, kp: 1.3}
    force: {kd: 0.0, ki: 0.0, kp: 0.0}
    position: {kd: 2.e-08, ki: 0.0, kp: 7.e-05}
    velocity: {kd: 1.25e-05, ki: 0.4, kp: 0.05}
  pelvis_2_motor:
    current: {kd: 0.0, ki: 520.0, kp: 1.3}
    force: {kd: 0.0, ki: 0.0, kp: 0.0}
    position: {kd: 2.e-08, ki: 0.0, kp: 7.e-05}
    velocity: {kd: 1.25e-05, ki: 0.4, kp: 0.05}
  arm_left_1_motor:
    current: {kd: 0.0, ki: 520.0, kp: 1.3}
    force: {kd: 0.0, ki: 0.0, kp: 0.0}
    position: {kd: 2.e-08, ki: 0.0, kp: 7.e-05}
    velocity: {kd: 1.25e-05, ki: 0.4, kp: 0.05}
  arm_left_2_motor:
    current: {kd: 0.0, ki: 520.0, kp: 1.3}
    force: {kd: 0.0, ki: 0.0, kp: 0.0}
    position: {kd: 2.e-08, ki: 0.0, kp: 7.e-05}
    velocity: {kd: 1.25e-05, ki: 0.4, kp: 0.05}
  arm_left_3_motor:
    current: {kd: 0.0, ki: 520.0, kp: 1.3}
    force: {kd: 0.0, ki: 0.0, kp: 0.0}
    position: {kd: 2.e-08, ki: 0.0, kp: 7.e-05}
    velocity: {kd: 1.25e-05, ki: 0.4, kp: 0.05}
  arm_left_4_motor:
    current: {kd: 0.0, ki: 520.0, kp: 1.3}
    force: {kd: 0.0, ki: 0.0, kp: 0.0}
    position: {kd: 2.e-08, ki: 0.0, kp: 7.e-05}
    velocity: {kd: 1.25e-05, ki: 0.4, kp: 0.05}
  arm_right_1_motor:
    current: {kd: 0.0, ki: 520.0, kp: 1.3}
    force: {kd: 0.0, ki: 0.0, kp: 0.0}
    position: {kd: 2.e-08, ki: 0.0, kp: 7.e-05}
    velocity: {kd: 1.25e-05, ki: 0.4, kp: 0.05}
  arm_right_2_motor:
    current: {kd: 0.0, ki: 520.0, kp: 1.3}
    force: {kd: 0.0, ki: 0.0, kp: 0.0}
    position: {kd: 2.e-08, ki: 0.0, kp: 7.e-05}
    velocity: {kd: 1.25e-05, ki: 0.4, kp: 0.05}
  arm_right_3_motor:
    current: {kd: 0.0, ki: 520.0, kp: 1.3}
    force: {kd: 0.0, ki: 0.0, kp: 0.0}
    position: {kd: 2.e-08, ki: 0.0, kp: 7.e-05}
    velocity: {kd: 1.25e-05, ki: 0.4, kp: 0.05}
  arm_right_4_motor:
    current: {kd: 0.0, ki: 520.0, kp: 1.3}
    force: {kd: 0.0, ki: 0.0, kp: 0.0}
    position: {kd: 2.e-08, ki: 0.0, kp: 7.e-05}
    velocity: {kd: 1.25e-05, ki: 0.4, kp: 0.05}
type: pal::ActuatorPIDCommandController

