gains:
  leg_left_1_joint: &leg_1_gains {p: 250, d: 5, i: 0.0, i_clamp: 3, torque_clamp: 50}
  leg_left_2_joint: &leg_2_gains {p: 500, d: 5, i: 0.0, i_clamp: 3, torque_clamp: 50}
  leg_left_3_joint: &leg_3_gains {p: 3000, d: 10, i: 0.2, i_clamp: 3, torque_clamp: 50}
  leg_left_4_joint: &leg_4_gains {p: 10000, d: 100, i: 1.0, i_clamp: 20, torque_clamp: 1000}
  leg_left_5_joint: &leg_5_gains {p: 120, d: 0.0, i: 0.02, i_clamp: 3, torque_clamp: 50}
  leg_left_6_joint: &leg_6_gains {p: 100, d: 0.02, i: 0.0, i_clamp: 3, torque_clamp: 50}
  leg_right_1_joint: *leg_1_gains
  leg_right_2_joint: *leg_2_gains
  leg_right_3_joint: *leg_3_gains
  leg_right_4_joint: *leg_4_gains
  leg_right_5_joint: *leg_5_gains
  leg_right_6_joint: *leg_6_gains