gains:
  leg_left_1_joint: {p: 250,  d: 5, i: 0.0, i_clamp: 3, torque_clamp: 50}
  leg_left_2_joint: {p: 500,  d: 5, i: 0.0, i_clamp: 3, torque_clamp: 50}
  leg_left_3_joint: {p: 2000,  d: 10, i: 0.0, i_clamp: 3, torque_clamp: 50}
  leg_left_4_joint: {p: 10000,  d: 50, i: 0.0, i_clamp: 20, torque_clamp: 1000}
  leg_left_5_joint: {p: 250,  d: 0.02, i: 0.1, i_clamp: 3, torque_clamp: 50}
  leg_left_6_joint: {p: 200,  d: 0.02, i: 0.0, i_clamp: 3, torque_clamp: 50}
  leg_right_1_joint: {p: 250,  d: 5, i: 0.0, i_clamp: 3, torque_clamp: 50}
  leg_right_2_joint: {p: 500,  d: 5, i: 0.0, i_clamp: 3, torque_clamp: 50}
  leg_right_3_joint: {p: 2000,  d: 10, i: 0.0, i_clamp: 3, torque_clamp: 50}
  leg_right_4_joint: {p: 10000,  d: 50, i: 0.0, i_clamp: 20, torque_clamp: 1000}
  leg_right_5_joint: {p: 250,  d: 0.02, i: 0.1, i_clamp: 3, torque_clamp: 50}
  leg_right_6_joint: {p: 200,  d: 0.02, i: 0.0, i_clamp: 3, torque_clamp: 50}
