ankle_params:
  motor_origin_offset_angle: !degrees 60.0
  m_O_TL1_angle: !degrees 5.0 
  pitch_offset_angle: !degrees 20.0
  TL2_BR1_BL1_angle: !degrees 60.0
  M_O: 0.0867 
  m_O: 0.035
  dx: 0.035
  dy: 0.060
  kho: 0.0425
  fbl_short: 0.060
  fbl_long: 0.380
  ball_screw_lead: 0.005
  ball_screw_efficiency: 0.9
  roll_min_angle: !degrees -25.0
  roll_max_angle: !degrees 25.0
  pitch_min_angle: !degrees -42.5
  pitch_max_angle: !degrees 42.5

leg_params:
  femur_length: 0.380
  fbl11_long: 0.40427
  fbl11_short: 0.09
  intersection_crank_axis: 0.22012
  fbl21_fixed: 0.115
  fbl21_long: 0.09
  fbl21_short: 0.04
  crank_slider_long: 0.215
  crank_slider_short: 0.090
  crank_slider_axis_angle: -0.191986217719376 
  shin_offset_angle: 0.0
  connection_fbl_offset_angle: -0.785398163397448 
  shin_fbl11_offset_angle: -0.261799387799149
  knee_angle_min: !degrees 15.0 # 5 degrees less than actual
  knee_angle_max: !degrees 145.0 # 5 degrees more than actual

left_hip_z_2023_params:
  Ly: &hipz_ly 0.10187
  offset_y: &hipz_offset_y 0.01883
  dy: &hipz_dy 0.040
  max_joint_angle: !degrees 45.0
  min_joint_angle: !degrees -15.0
  zero_joint_offset: &hipz_2023_zero_joint_offset !degrees 16.0

right_hip_z_2023_params:
  Ly: *hipz_ly
  offset_y: *hipz_offset_y
  dy: *hipz_dy
  max_joint_angle: !degrees 15.0
  min_joint_angle: !degrees -45.0
  zero_joint_offset: *hipz_2023_zero_joint_offset

left_hip_z_2022_params:
  Ly: &hipz_2022_ly 0.09639
  offset_y: &hipz_2022_offset_y 0.00087
  dy: &hipz_2022_dy 0.040
  max_joint_angle: !degrees 45.0
  min_joint_angle: !degrees -15.0
  zero_joint_offset: &hipz_2022_zero_joint_offset !degrees 24.0

right_hip_z_2022_params:
  Ly: *hipz_2022_ly
  offset_y: *hipz_2022_offset_y
  dy: *hipz_2022_dy
  max_joint_angle: !degrees 15.0
  min_joint_angle: !degrees -45.0
  zero_joint_offset: *hipz_2022_zero_joint_offset
