walking_controller:
  type: walking_controller/ReemcControl
  joints:
    - leg_left_1_joint
    - leg_left_2_joint
    - leg_left_3_joint
    - leg_left_length_joint
    - leg_left_4_joint
    - leg_left_5_joint
    - leg_right_1_joint
    - leg_right_2_joint
    - leg_right_3_joint
    - leg_right_length_joint
    - leg_right_4_joint
    - leg_right_5_joint
  left_ft_sensor: left_ankle_ft
  right_ft_sensor: right_ankle_ft
  base_imu_sensor: base_imu
  tree_tips: ["leg_left_5_link", "leg_right_5_link"]
  check_mode: False
  actuators:
    - leg_left_1_motor
    - leg_left_2_motor
    - leg_left_3_motor
    - leg_left_length_motor
    - leg_left_4_motor
    - leg_left_5_motor
    - leg_right_1_motor
    - leg_right_2_motor
    - leg_right_3_motor
    - leg_right_length_motor
    - leg_right_4_motor
    - leg_right_5_motor
