imu:
  base_imu:
    frame: imu_link
    gazebo_sensor_name: imu_sensor

force_torque:
  left_ankle_ft:
    sensor_joint: left_ft_sensor_joint
    frame: left_ft_sensor_link
  right_ankle_ft:
    sensor_joint: right_ft_sensor_joint
    frame: right_ft_sensor_link

