<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="kangaroo">

<xacro:property name="foot_length"   value="0.21" />
<xacro:property name="foot_width"   value="0.09" />

<xacro:macro name="kangaroo_foot_frames" params="side parent offset_x:=0.0 offset_y:=0.0">

	<link name="${side}_foot_upper_left"/>
	<link name="${side}_foot_upper_right"/>
	<link name="${side}_foot_lower_left"/>
	<link name="${side}_foot_lower_right"/>

	<joint name="${side}_foot_upper_left_fix_joint" type="fixed">
		<parent link="${side}_sole_link" />
		<child link="${side}_foot_upper_left" />
		<origin xyz="${foot_length/2. + offset_x} ${foot_width/2. + offset_y} 0.0" rpy="0 0 0" />
	</joint>

	<joint name="${side}_foot_upper_right_fix_joint" type="fixed">
		<parent link="${side}_sole_link" />
		<child link="${side}_foot_upper_right" />
		<origin xyz="${foot_length/2. + offset_x} ${-foot_width/2. + offset_y} 0.0" rpy="0 0 0" />
	</joint>

	<joint name="${side}_foot_lower_left_fix_joint" type="fixed">
		<parent link="${side}_sole_link" />
		<child link="${side}_foot_lower_left" />
		<origin xyz="${-foot_length/2. + offset_x} ${foot_width/2. + offset_y} 0.0" rpy="0 0 0" />
	</joint>

	<joint name="${side}_foot_lower_right_fix_joint" type="fixed">
		<parent link="${side}_sole_link" />
		<child link="${side}_foot_lower_right" />
		<origin xyz="${-foot_length/2. + offset_x} ${-foot_width/2. + offset_y} 0.0" rpy="0 0 0" />
	</joint>

</xacro:macro>

</robot>
