right_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  check_mode: True
  joints:
    - arm_right_1_joint
    - arm_right_2_joint
    - arm_right_3_joint
    - arm_right_4_joint
  actuators:
    - arm_right_1_motor
    - arm_right_2_motor
    - arm_right_3_motor
    - arm_right_4_motor
  constraints:
    goal_time: &goal_time_constraint 0.6
    stopped_velocity_tolerance: &stopped_velocity_constraint 0.05
    arm_right_1_joint:
      goal: &goal_pos_constraint 0.02
    arm_right_2_joint:
      goal: *goal_pos_constraint
    arm_right_3_joint:
      goal: *goal_pos_constraint
    arm_right_4_joint:
      goal: *goal_pos_constraint

  stop_trajectory_duration: 0.0
